### ISSUE TITLE
add a button to the image toolbar [question]

### ISSUE THREAD

**Issue by wc-matteo** [SamhammerAG/ckeditor5-simple-button-plugin#1]
is there a way to add a button (through this plugin) to the image contextual toolbar?

This one:
![image](https://user-images.githubusercontent.com/10562635/132507327-52e9c847-0deb-4340-83f6-c5486a85b2a6.png)

**Comment by ckotzbauer** [comment]
I'm not sure about this, but when reading the ckeditor5 code, it can be achieved, with prefixing the name of the button-definition you define in the config. https://github.com/ckeditor/ckeditor5/blob/master/packages/ckeditor5-alignment/src/alignmentui.js#L132
